### ISSUE TITLE
Specify latent space variables in generate.py

### ISSUE THREAD

**Issue by ajerschow** [PDillis/stylegan3-fun#25]
It was not clear to me how I could specify the latent space variables to generate.py, because it seems you can only provide a seed. Can I provide arguments or ranges to generate.py corresponding to the two latent space variables that one can control in visualizer.py?
Thank you & sorry if this is an obvious question.

**Comment by PDillis** [comment]
Hello! Sorry for not seeing this before. 

`generate.py` lets you either generate images/grid of images (`python generate.py images ...`) or videos (`python generate.py {random-video/circular-video} ...`). Each have their own set of parameters you can set in order to get what you want. I'm not sure what you mean with the two latent space variables in `visualizer.py`. Do you mean seed and style mixing, or the truncation? If it's anything to do with style mixing, then that's what `style_mixing.py` is for. For the other two, they have available settings/commands in `generate.py`. 

Let me know! I haven't fully documented this, so for sure it's not an obvious question.

**Comment by ajerschow** [comment]
Thank you for your reply. I am showing the screenshot from visualizer.py from your GitHub page below. 

How would I set the two numbers of latent space that are circled in the screenshot. How could I control them in `generate.py images` or `generate.py circular-video` ( the numbers in this screenshot are -0.38, -0.04, the ones that one can control in visualizer by dragging the mouse over the image)?

Thank you
Alexej

**Comment by PDillis** [comment]
Ah, I see what you mean. I haven't added any of this to the scripts, as these are heuristics on the GUI on how to interpolate between seeds. As you click and drag the mouse, you are slowly interpolating/changing the seeds, so you could check the code to see how this is explicitly done over at [`viz/latent_widget.py`](https://github.com/PDillis/stylegan3-fun/blob/main/viz/latent_widget.py). 

So, if you want to interpolate between seeds with my scripts, you should check [`sightseeding.py`](https://github.com/PDillis/stylegan3-fun/blob/main/sightseeding.py). You won't have the minute level of control from the GUI, as honestly it's done for 2D interactions with the latent space (i.e., the screen), which doesn't translate well to the command line. However, I believe I give a lot of usability in how you interpolate between them, so I hope it's useful for you as well. I provide some examples in my previous repo [here](https://github.com/PDillis/stylegan2-fun#sightseeding). 

If you are interested in a specific frame of the video, you could then use `ffmpeg` to extract all frames and select the one you want. Some examples can be found [here](https://stackoverflow.com/questions/40088222/ffmpeg-convert-video-to-images). Let me know if you have other issues/questions!

**Comment by ajerschow** [comment]
Thank you, that clears it up!
